import test from 'node:test';import assert from 'node:assert/strict';import{evaluatePreproductionEvidence,productionVerificationRequired}from'../preproduction-completion';
const now='2026-09-25T00:00:00Z';
const base={customAdminResponsive:true,portfolioSixSites:true,futureSiteConnector:true,githubTraceability:true,externalBlockersLabeled:true};
const signal:any={id:'g1',siteId:'pilot',category:'cro',title:'Improve signup',description:'Observed funnel drop',evidence:[{source:'analytics',observedAt:now,url:'https://example.test/report'}],impact:4,confidence:4,effort:2,recurringCostUsd:0,risk:2,successMetric:'signup conversion rate',approvalClass:'amber'};
const structured:any={discovery:{siteId:'pilot',capturedAt:now,routes:['/'],evidenceCount:1},competitors:{capturedAt:now,competitors:[{domain:'peer.test',evidenceUrls:['https://peer.test/pricing']}]},packages:{capturedAt:now,plans:['free','pro','business'],recommendationEvidence:['pricing-gap']},entitlements:{checkedAt:now,freeDeniedPaidFeature:true,proAllowedPaidFeature:true,businessAllowedPaidFeature:true,emergencyKillDenied:true},growthWorkflow:{siteId:'pilot',capturedAt:now,signals:[signal],actions:[{signalId:'g1',siteId:'pilot',title:'Improve signup',category:'cro',score:80,approvalClass:'amber',successMetric:'signup conversion rate',evidenceCount:1}]},security:{connectorAuthentication:true,rbac:true,crossSiteIsolation:true,auditRedaction:true,recoveryRollback:true,httpsProduction:true,fileEditingDisabled:true},responsiveAdmin:{checkedAt:now,viewports:[{width:390,height:844,navigationUsable:true,contentFits:true},{width:800,height:1280,navigationUsable:true,contentFits:true},{width:1440,height:900,navigationUsable:true,contentFits:true}]},connectorContract:{checkedAt:now,transportValidated:true,authorizationSeparated:true,siteScoped:true,replayProtected:true},githubTrace:{checkedAt:now,commitSha:'ae28576d',pullRequestNumber:44,ciRunId:36088562991,ciPassed:true},externalBlockers:[],livePortfolio:[{id:1,domain:'barcodeqrhub.com'},{id:2,domain:'priceinsight360.com'},{id:3,domain:'businessstarttools.com'},{id:4,domain:'aitoolstores.com'},{id:5,domain:'pdfimagetools.online'},{id:6,domain:'calcumint.com'}]};
test('fails closed when structured evidence is missing',()=>{const r=evaluatePreproductionEvidence({gates:{customAdminResponsive:true}});assert.equal(r.complete,false);assert.ok(r.missing.includes('pilotDiscoveryEvidence'))});
test('boolean claims cannot bypass structured evidence gates',()=>{const r=evaluatePreproductionEvidence({gates:{...base,pilotDiscoveryEvidence:true,competitorSnapshots:true,packageRecommendations:true,entitlementEnforcement:true,realGrowthWorkflows:true,securityAuditRollback:true}});for(const key of ['pilotDiscoveryEvidence','competitorSnapshots','packageRecommendations','entitlementEnforcement','realGrowthWorkflows','securityAuditRollback'] as const)assert.ok(r.missing.includes(key))});
test('valid structured evidence leaves production verification as final external gate',()=>{const r=evaluatePreproductionEvidence({gates:base,...structured});assert.equal(productionVerificationRequired(r.results),true);assert.equal(r.results.filter(x=>x.status==='fail').length,0)});
test('incomplete security evidence blocks security audit rollback gate',()=>{const r=evaluatePreproductionEvidence({gates:base,...structured,security:{...structured.security,recoveryRollback:false}});assert.ok(r.missing.includes('securityAuditRollback'))});

test('portfolio boolean cannot bypass live six-site verification',()=>{const r=evaluatePreproductionEvidence({gates:{...base,portfolioSixSites:true},...structured,livePortfolio:structured.livePortfolio.slice(0,5)});assert.ok(r.missing.includes('portfolioSixSites'))});
