import test from 'node:test';import assert from 'node:assert/strict';import { WordPressGrowthOSClient, readWordPressGrowthOSConfig } from '../wordpress-growthos-client';

test('requires HTTPS configuration',()=>assert.throws(()=>readWordPressGrowthOSConfig({GROWTHOS_WORDPRESS_URL:'http://example.com',GROWTHOS_WORDPRESS_USERNAME:'u',GROWTHOS_WORDPRESS_APPLICATION_PASSWORD:'p'}),/WORDPRESS_HTTPS_REQUIRED/));
test('returns null when connector credentials are incomplete',()=>assert.equal(readWordPressGrowthOSConfig({GROWTHOS_WORDPRESS_URL:'https://example.com',GROWTHOS_WORDPRESS_USERNAME:'',GROWTHOS_WORDPRESS_APPLICATION_PASSWORD:'p'}),null));
test('normalizes configured WordPress origin',()=>assert.deepEqual(readWordPressGrowthOSConfig({GROWTHOS_WORDPRESS_URL:'https://example.com/path/',GROWTHOS_WORDPRESS_USERNAME:'growth',GROWTHOS_WORDPRESS_APPLICATION_PASSWORD:'secret'}),{baseUrl:'https://example.com',username:'growth',applicationPassword:'secret'}));
test('sends application-password authentication and site query',async()=>{const original=globalThis.fetch;let seenUrl='';let seenHeaders:HeadersInit|undefined;globalThis.fetch=(async(input,init)=>{seenUrl=String(input);seenHeaders=init?.headers;return new Response(JSON.stringify({ok:true}),{status:200})}) as typeof fetch;try{const client=new WordPressGrowthOSClient({baseUrl:'https://example.com',username:'growth',applicationPassword:'secret'});await client.dashboard(6);assert.equal(seenUrl,'https://example.com/wp-json/growthos/v1/dashboard?site_id=6');assert.equal((seenHeaders as Record<string,string>).Authorization,'Basic Z3Jvd3RoOnNlY3JldA==')}finally{globalThis.fetch=original}});
test('rejects unauthorized connector responses',async()=>{const original=globalThis.fetch;globalThis.fetch=(async()=>new Response('{}',{status:401})) as typeof fetch;try{const client=new WordPressGrowthOSClient({baseUrl:'https://example.com',username:'growth',applicationPassword:'secret'});await assert.rejects(client.sites(),/WORDPRESS_UNAUTHORIZED/)}finally{globalThis.fetch=original}});

test('readiness uses authenticated read-only production endpoint',async()=>{const original=globalThis.fetch;let seen='';globalThis.fetch=(async(input)=>{seen=String(input);return new Response(JSON.stringify({ready:true,checks:[]}),{status:200})}) as typeof fetch;try{const client=new WordPressGrowthOSClient({baseUrl:'https://growthos.converentis.com',username:'growth',applicationPassword:'secret'});await client.readiness();assert.equal(seen,'https://growthos.converentis.com/wp-json/growthos/v1/readiness')}finally{globalThis.fetch=original}});
