<?php
if (!defined('ABSPATH')) exit;
final class GrowthOS_Engines {
 public static function register(): void { add_filter('growthos_execute_job',[self::class,'execute'],10,4); }
 public static function execute($result,string $type,array $payload,array $job){
  if(!in_array($type,['discovery_scan','qa_scan','seo_scan','competitor_scan','growth_scan'],true))return $result;
  $site=(int)($job['site_id']??0);if(!$site)throw new RuntimeException('SITE_REQUIRED');
  global $wpdb;$sites=$wpdb->prefix.'growthos_sites';$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM $sites WHERE id=%d",$site),ARRAY_A);if(!$row)throw new RuntimeException('SITE_NOT_FOUND');
  $labels=['discovery_scan'=>'discovery','qa_scan'=>'qa','seo_scan'=>'seo','competitor_scan'=>'competitor','growth_scan'=>'growth'];
  if($type==='discovery_scan')return self::discover($row);
  if(in_array($type,['qa_scan','seo_scan'],true))return self::analyze($row,$labels[$type]);
  return ['engine'=>$labels[$type],'site_id'=>$site,'domain'=>$row['domain'],'status'=>'ready_for_connector','message'=>'Engine dispatch verified; external evidence connector required.'];
 }
 private static function analyze(array $site,string $engine): array {
  global $wpdb;$d=$wpdb->prefix.'growthos_discoveries';$r=$wpdb->prefix.'growthos_recommendations';$pages=$wpdb->get_results($wpdb->prepare("SELECT * FROM $d WHERE site_id=%d AND id IN (SELECT MAX(id) FROM $d WHERE site_id=%d GROUP BY url) ORDER BY id DESC LIMIT 200",$site['id'],$site['id']),ARRAY_A);if(!$pages)throw new RuntimeException('DISCOVERY_REQUIRED');
  $deduped=[];foreach($pages as $page){$key=self::normalize_url((string)$page['url']);if(!isset($deduped[$key]))$deduped[$key]=$page;}$pages=array_values($deduped);
  $findings=[];foreach($pages as $page){
   if($engine==='seo'){$ev=json_decode((string)$page['evidence'],true)?:[];if(stripos((string)($ev['x_robots_tag']??''),'noindex')!==false)$findings[]=['title'=>'Page sends a noindex X-Robots-Tag','score'=>90,'page'=>$page];if(trim((string)$page['title'])==='')$findings[]=['title'=>'Page is missing a title','score'=>95,'page'=>$page];if(trim((string)$page['meta_description'])==='')$findings[]=['title'=>'Page is missing a meta description','score'=>75,'page'=>$page];if((int)$page['h1_count']!==1)$findings[]=['title'=>'Page should have one primary H1','score'=>65,'page'=>$page];if(trim((string)$page['canonical'])==='')$findings[]=['title'=>'Page canonical was not detected','score'=>70,'page'=>$page];}
   if($engine==='qa'){$ev=json_decode((string)$page['evidence'],true)?:[];if((int)$page['http_status']<200||(int)$page['http_status']>=400)$findings[]=['title'=>'Page returned an unhealthy HTTP status','score'=>100,'page'=>$page];if((int)$page['word_count']<100)$findings[]=['title'=>'Page has unusually little indexable text','score'=>55,'page'=>$page];if(stripos((string)($ev['x_robots_tag']??''),'noindex')!==false)$findings[]=['title'=>'Page is blocked from indexing by X-Robots-Tag','score'=>90,'page'=>$page];}
  }
  if($engine==='seo'){
   $titles=[];$descs=[];foreach($pages as $p){$t=trim((string)$p['title']);$m=trim((string)$p['meta_description']);if($t!=='')$titles[$t][]=$p;if($m!=='')$descs[$m][]=$p;if($p['canonical']!==''&&!self::same_host((string)$p['canonical'],$site['domain']))$findings[]=['title'=>'Canonical points outside the registered domain','score'=>85,'page'=>$p];if(strlen($t)>60)$findings[]=['title'=>'Page title is unusually long','score'=>45,'page'=>$p];if(strlen($m)>160)$findings[]=['title'=>'Meta description is unusually long','score'=>35,'page'=>$p];}
   foreach($titles as $group)if(count($group)>1)foreach($group as $p)$findings[]=['title'=>'Duplicate page title detected','score'=>70,'page'=>$p];
   foreach($descs as $group)if(count($group)>1)foreach($group as $p)$findings[]=['title'=>'Duplicate meta description detected','score'=>55,'page'=>$p];
  }
  foreach(array_slice($findings,0,100) as $x){$page=$x['page'];$title=$x['title'].' — '.$page['url'];$exists=$wpdb->get_var($wpdb->prepare("SELECT id FROM $r WHERE site_id=%d AND category=%s AND title=%s AND status='proposed' LIMIT 1",$site['id'],$engine,$title));if(!$exists)$wpdb->insert($r,['site_id'=>$site['id'],'category'=>$engine,'title'=>$title,'evidence'=>wp_json_encode(['discovery_id'=>$page['id'],'url'=>$page['url']]),'score'=>$x['score'],'approval_class'=>'amber','status'=>'proposed']);}
  return ['engine'=>$engine,'site_id'=>(int)$site['id'],'status'=>'completed','findings'=>count($findings)];
 }
 private static function discover(array $site): array {
  global $wpdb;$base='https://'.$site['domain'];$urls=[$base];$robots=self::robots($base);$sitemaps=$robots['sitemaps']?:[$base.'/sitemap.xml'];$queue=array_slice($sitemaps,0,5);$seen_maps=[];
  while($queue&&count($seen_maps)<10&&count($urls)<50){$map=array_shift($queue);if(isset($seen_maps[$map])||!self::same_host($map,$site['domain']))continue;$seen_maps[$map]=1;$sm=wp_safe_remote_get($map,['timeout'=>10,'redirection'=>2,'user-agent'=>'GrowthOS/1.0']);if(is_wp_error($sm)||(int)wp_remote_retrieve_response_code($sm)!==200)continue;$xml=(string)wp_remote_retrieve_body($sm);if(preg_match_all('~<loc>\s*(.*?)\s*</loc>~i',$xml,$m))foreach($m[1] as $u){$u=html_entity_decode(trim($u));if(!self::same_host($u,$site['domain']))continue;if(preg_match('~\.xml(?:\.gz)?(?:\?|$)~i',$u)){if(count($seen_maps)+count($queue)<10)$queue[]=$u;}elseif(count($urls)<50)$urls[]=$u;}}
  $normalized=[];foreach($urls as $u){$n=self::normalize_url((string)$u);if($n!=='')$normalized[$n]=$n;}$urls=array_values($normalized);$saved=0;$errors=0;$linked=[];
  foreach($urls as $url){if(self::blocked($url,$robots['disallow']))continue;$response=wp_safe_remote_get($url,['timeout'=>12,'redirection'=>3,'user-agent'=>'GrowthOS/1.0']);if(is_wp_error($response)){$errors++;continue;}$status=(int)wp_remote_retrieve_response_code($response);$body=(string)wp_remote_retrieve_body($response);$title='';$description='';$canonical='';$h1=0;$words=0;$links=0;
   if(class_exists('DOMDocument')&&$body!==''){$dom=new DOMDocument();libxml_use_internal_errors(true);$dom->loadHTML($body);libxml_clear_errors();$titles=$dom->getElementsByTagName('title');if($titles->length)$title=trim($titles->item(0)->textContent);$h1=$dom->getElementsByTagName('h1')->length;$words=str_word_count(wp_strip_all_tags($body));foreach($dom->getElementsByTagName('meta') as $m)if(strtolower($m->getAttribute('name'))==='description')$description=trim($m->getAttribute('content'));foreach($dom->getElementsByTagName('link') as $l)if(strtolower($l->getAttribute('rel'))==='canonical')$canonical=trim($l->getAttribute('href'));foreach($dom->getElementsByTagName('a') as $a){$href=trim($a->getAttribute('href'));if($href==='')continue;$abs=self::absolute_url($href,$url);if($abs&&self::same_host($abs,$site['domain'])){$links++;if(count($linked)<100)$linked[$abs]=1;}}}
   $fingerprint=hash('sha256',$body);$table=$wpdb->prefix.'growthos_discoveries';$prior=$wpdb->get_var($wpdb->prepare("SELECT id FROM $table WHERE site_id=%d AND url=%s AND fingerprint=%s ORDER BY id DESC LIMIT 1",$site['id'],$url,$fingerprint));if($prior)continue;
   $data=['site_id'=>(int)$site['id'],'url'=>$url,'page_type'=>$url===$base?'homepage':'page','http_status'=>$status,'title'=>$title,'meta_description'=>$description,'canonical'=>$canonical,'h1_count'=>$h1,'word_count'=>$words,'evidence'=>wp_json_encode(['content_type'=>wp_remote_retrieve_header($response,'content-type'),'internal_links'=>$links,'robots_observed'=>true,'x_robots_tag'=>wp_remote_retrieve_header($response,'x-robots-tag'),'redirected_to'=>wp_remote_retrieve_header($response,'location')]),'fingerprint'=>$fingerprint,'discovered_at'=>current_time('mysql')];if(false!==$wpdb->insert($table,$data))$saved++;else $errors++;
  }
  return ['engine'=>'discovery','site_id'=>(int)$site['id'],'status'=>'completed','urls_seen'=>count($urls),'pages_saved'=>$saved,'internal_urls_found'=>count($linked),'sitemaps_seen'=>count($seen_maps),'robots_found'=>$robots['found'],'errors'=>$errors];
 }
 private static function robots(string $base): array {$out=['found'=>false,'disallow'=>[],'sitemaps'=>[]];$r=wp_safe_remote_get($base.'/robots.txt',['timeout'=>8,'redirection'=>2,'user-agent'=>'GrowthOS/1.0']);if(is_wp_error($r)||(int)wp_remote_retrieve_response_code($r)!==200)return $out;$out['found']=true;$active=false;foreach(preg_split('/\r\n|\r|\n/',(string)wp_remote_retrieve_body($r)) as $line){$line=trim(preg_replace('/#.*/','',$line));if(stripos($line,'User-agent:')===0)$active=trim(substr($line,11))==='*';elseif($active&&stripos($line,'Disallow:')===0){$v=trim(substr($line,9));if($v!=='')$out['disallow'][]=$v;}elseif(stripos($line,'Sitemap:')===0){$v=trim(substr($line,8));if($v!=='')$out['sitemaps'][]=$v;}}return $out;}
 private static function blocked(string $url,array $rules): bool {$path=(string)wp_parse_url($url,PHP_URL_PATH);foreach($rules as $rule)if($rule!=='/'&&str_starts_with($path,$rule))return true;return in_array('/',$rules,true);}
 private static function absolute_url(string $href,string $page): ?string {if(preg_match('~^(mailto:|tel:|javascript:|#)~i',$href))return null;if(preg_match('~^https?://~i',$href))return strtok($href,'#');$scheme=(string)wp_parse_url($page,PHP_URL_SCHEME);$host=(string)wp_parse_url($page,PHP_URL_HOST);if(str_starts_with($href,'//'))return $scheme.':'.$href;if(str_starts_with($href,'/'))return $scheme.'://'.$host.$href;$path=(string)wp_parse_url($page,PHP_URL_PATH);$dir=rtrim(str_replace('\\','/',dirname($path)),'/');return $scheme.'://'.$host.($dir?'/'.ltrim($dir,'/'):'').'/'.$href;}
 private static function normalize_url(string $url): string {$url=trim($url);if($url==='')return '';$parts=wp_parse_url($url);if(!is_array($parts)||empty($parts['host']))return $url;$scheme=strtolower((string)($parts['scheme']??'https'));$host=strtolower((string)$parts['host']);$port=isset($parts['port'])?':'.(int)$parts['port']:'';$path=(string)($parts['path']??'/');if($path==='')$path='/';if($path!=='/')$path=rtrim($path,'/');$query=isset($parts['query'])&&$parts['query']!==''?'?'.$parts['query']:'';return $scheme.'://'.$host.$port.$path.$query;}
 private static function same_host(string $url,string $domain): bool {$host=strtolower((string)wp_parse_url($url,PHP_URL_HOST));$domain=strtolower($domain);return $host===$domain||$host==='www.'.$domain||('www.'.$host)===$domain;}

}
GrowthOS_Engines::register();
