<?php
if (!defined('ABSPATH')) exit;
final class GrowthOS_DB {
 public static function maybe_upgrade(): void { if((string)get_option('growthos_db_version','0')!==(string)GROWTHOS_DB_VERSION) self::install(false); }
 public static function activate(): void { self::install(true); }
 private static function install(bool $flush): void {
  global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php';
  $c=$wpdb->get_charset_collate(); $p=$wpdb->prefix.'growthos_';
  dbDelta("CREATE TABLE {$p}sites (id bigint unsigned NOT NULL AUTO_INCREMENT, name varchar(190) NOT NULL, domain varchar(255) NOT NULL, status varchar(32) NOT NULL DEFAULT 'active', created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY domain(domain)) $c;");
  dbDelta("CREATE TABLE {$p}recommendations (id bigint unsigned NOT NULL AUTO_INCREMENT, site_id bigint unsigned NOT NULL, category varchar(64) NOT NULL, title text NOT NULL, evidence longtext NULL, score decimal(8,2) NOT NULL DEFAULT 0, approval_class varchar(16) NOT NULL DEFAULT 'green', status varchar(32) NOT NULL DEFAULT 'proposed', created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), KEY site_status(site_id,status)) $c;");
  dbDelta("CREATE TABLE {$p}approvals (id bigint unsigned NOT NULL AUTO_INCREMENT, recommendation_id bigint unsigned NOT NULL, actor_id bigint unsigned NOT NULL, decision varchar(16) NOT NULL, note text NULL, idempotency_key varchar(190) NOT NULL, created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY idempotency_key(idempotency_key)) $c;");
  dbDelta("CREATE TABLE {$p}features (id bigint unsigned NOT NULL AUTO_INCREMENT, site_id bigint unsigned NOT NULL, feature_key varchar(190) NOT NULL, name varchar(190) NOT NULL, state varchar(32) NOT NULL DEFAULT 'on', free_enabled tinyint(1) NOT NULL DEFAULT 1, pro_enabled tinyint(1) NOT NULL DEFAULT 1, business_enabled tinyint(1) NOT NULL DEFAULT 1, quota_json longtext NULL, rollout_percent smallint unsigned NOT NULL DEFAULT 100, status_message text NULL, updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY site_feature(site_id,feature_key)) $c;");
  dbDelta("CREATE TABLE {$p}connectors (id bigint unsigned NOT NULL AUTO_INCREMENT, site_id bigint unsigned NOT NULL, kind varchar(64) NOT NULL, status varchar(32) NOT NULL DEFAULT 'needs_connection', last_seen_at datetime NULL, last_error text NULL, created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY site_kind(site_id,kind)) $c;");
  dbDelta("CREATE TABLE {$p}jobs (id bigint unsigned NOT NULL AUTO_INCREMENT, site_id bigint unsigned NULL, job_type varchar(190) NOT NULL, status varchar(32) NOT NULL DEFAULT 'queued', payload longtext NULL, result longtext NULL, error text NULL, attempts smallint unsigned NOT NULL DEFAULT 0, max_attempts smallint unsigned NOT NULL DEFAULT 3, idempotency_key varchar(190) NULL, created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY idempotency_key(idempotency_key), KEY job_status(status,created_at)) $c;");
  dbDelta("CREATE TABLE {$p}discoveries (id bigint unsigned NOT NULL AUTO_INCREMENT, site_id bigint unsigned NOT NULL, url text NOT NULL, page_type varchar(64) NULL, http_status smallint unsigned NULL, title text NULL, meta_description text NULL, canonical text NULL, h1_count smallint unsigned NOT NULL DEFAULT 0, word_count int unsigned NOT NULL DEFAULT 0, evidence longtext NULL, fingerprint varchar(64) NULL, discovered_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), KEY site_discovered(site_id,discovered_at)) $c;");
  dbDelta("CREATE TABLE {$p}competitors (id bigint unsigned NOT NULL AUTO_INCREMENT, site_id bigint unsigned NOT NULL, name varchar(190) NOT NULL, domain varchar(190) NOT NULL, evidence_url text NULL, status varchar(32) NOT NULL DEFAULT 'active', verified_at datetime NULL, created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY site_domain(site_id,domain), KEY site_status(site_id,status)) $c;");
  dbDelta("CREATE TABLE {$p}competitor_packages (id bigint unsigned NOT NULL AUTO_INCREMENT, competitor_id bigint unsigned NOT NULL, plan_key varchar(64) NOT NULL, plan_name varchar(190) NOT NULL, price_amount decimal(12,2) NULL, currency varchar(8) NULL, billing_period varchar(32) NULL, features longtext NULL, evidence_url text NULL, observed_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY competitor_plan(competitor_id,plan_key)) $c;");
  dbDelta("CREATE TABLE {$p}executions (id bigint unsigned NOT NULL AUTO_INCREMENT, recommendation_id bigint unsigned NOT NULL, site_id bigint unsigned NOT NULL, status varchar(32) NOT NULL DEFAULT 'ready', implementation_type varchar(64) NULL, implementation_ref varchar(255) NULL, verification_status varchar(32) NOT NULL DEFAULT 'pending', verification_evidence longtext NULL, started_at datetime NULL, completed_at datetime NULL, created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY recommendation(recommendation_id), KEY site_status(site_id,status)) $c;");
  dbDelta("CREATE TABLE {$p}measurements (id bigint unsigned NOT NULL AUTO_INCREMENT, execution_id bigint unsigned NOT NULL, site_id bigint unsigned NOT NULL, metric_key varchar(190) NOT NULL, baseline_value decimal(18,4) NULL, observed_value decimal(18,4) NULL, unit varchar(32) NULL, window_start datetime NULL, window_end datetime NULL, evidence longtext NULL, created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), KEY execution_metric(execution_id,metric_key), KEY site_created(site_id,created_at)) $c;");
  dbDelta("CREATE TABLE {$p}metric_goals (id bigint unsigned NOT NULL AUTO_INCREMENT, site_id bigint unsigned NOT NULL, metric_key varchar(190) NOT NULL, direction varchar(16) NOT NULL DEFAULT 'increase', unit varchar(32) NULL, target_value decimal(20,6) NULL, created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY site_metric(site_id,metric_key)) $c;");
  dbDelta("CREATE TABLE {$p}revenue_events (id bigint unsigned NOT NULL AUTO_INCREMENT, site_id bigint unsigned NOT NULL, execution_id bigint unsigned NULL, event_type varchar(64) NOT NULL, amount decimal(20,6) NOT NULL DEFAULT 0, currency varchar(8) NOT NULL, source varchar(64) NULL, attribution_method varchar(32) NOT NULL DEFAULT 'observed_correlation', evidence longtext NOT NULL, occurred_at datetime NOT NULL, created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), KEY site_occurred(site_id,occurred_at), KEY execution_event(execution_id,event_type)) $c;");
  dbDelta("CREATE TABLE {$p}cost_events (id bigint unsigned NOT NULL AUTO_INCREMENT, site_id bigint unsigned NOT NULL, execution_id bigint unsigned NULL, cost_type varchar(64) NOT NULL, amount decimal(20,6) NOT NULL DEFAULT 0, currency varchar(8) NOT NULL, evidence longtext NOT NULL, occurred_at datetime NOT NULL, created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), KEY site_occurred(site_id,occurred_at), KEY execution_cost(execution_id,cost_type)) $c;");
  dbDelta("CREATE TABLE {$p}audit_events (id bigint unsigned NOT NULL AUTO_INCREMENT, actor_id bigint unsigned NULL, site_id bigint unsigned NULL, action varchar(190) NOT NULL, object_type varchar(64) NOT NULL, object_id varchar(190) NULL, before_data longtext NULL, after_data longtext NULL, created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), KEY site_created(site_id,created_at)) $c;");

  // Normalize legacy duplicate competitor plans before enforcing the unique plan key.
  $pkg=$p.'competitor_packages';if($wpdb->get_var($wpdb->prepare("SHOW TABLES LIKE %s",$pkg))===$pkg){$dupes=$wpdb->get_results("SELECT competitor_id,plan_key,MAX(id) keep_id FROM $pkg GROUP BY competitor_id,plan_key HAVING COUNT(*)>1",ARRAY_A);foreach($dupes as $d){$wpdb->query($wpdb->prepare("DELETE FROM $pkg WHERE competitor_id=%d AND plan_key=%s AND id<>%d",(int)$d['competitor_id'],$d['plan_key'],(int)$d['keep_id']));}}
  $admin=get_role('administrator'); if($admin){$admin->add_cap('growthos_access');$admin->add_cap('growthos_approve');$admin->add_cap('growthos_manage');}
  update_option('growthos_db_version',GROWTHOS_DB_VERSION);
  if($flush)flush_rewrite_rules();
 }
}
