'use client';
import { useEffect, useMemo, useState } from 'react';
import { growthSites as sites } from '../core/portfolio';
import { resolveSiteScope, siteScopeOptions } from '../core/site-scope';
import { ApprovalInboxPanel } from './approval-inbox-panel';
import { buildApprovalInboxViewModel } from '../core/approval-inbox-view';
import type { DashboardSnapshot } from '../core/dashboard-repository';

type Section='home'|'websites'|'growth'|'automation'|'settings';
const nav:[Section,string,string][]=[['home','Home','⌂'],['websites','Websites','▦'],['growth','Growth','↗'],['automation','Automation','▶'],['settings','Settings','⚙']];
const growthAreas=['SEO & visibility','CRO & experimentation','Competitors & packages','Content & lifecycle','Revenue & impact'];
const settingsAreas=['Connections','Features & plans','Security & audit','System readiness'];

export default function Dashboard(){
 const [section,setSection]=useState<Section>('home');const [siteId,setSiteId]=useState('');const [snapshot,setSnapshot]=useState<DashboardSnapshot|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const selectedSite=useMemo(()=>resolveSiteScope(sites,siteId||undefined),[siteId]);
 useEffect(()=>{const hash=window.location.hash.replace('#','') as Section;if(nav.some(([id])=>id===hash))setSection(hash)},[]);
 useEffect(()=>{let active=true;setLoading(true);setError('');const query=siteId?'?siteId='+encodeURIComponent(siteId):'';fetch('/api/dashboard'+query,{credentials:'include',cache:'no-store'}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.message||body.code||'DASHBOARD_FAILED');return body;}).then(body=>{if(active)setSnapshot(body.data)}).catch(e=>{if(active){setSnapshot(null);setError(e instanceof Error?e.message:'DASHBOARD_FAILED')}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[siteId]);
 const counts=snapshot?.counts;const approvals=buildApprovalInboxViewModel((snapshot?.approvalInbox??[]).filter(x=>x.approvalClass!=='green').map(x=>({...x,approvalClass:x.approvalClass as 'amber'|'red'})));
 const go=(next:Section)=>{setSection(next);window.history.replaceState(null,'','#'+next);window.scrollTo({top:0,behavior:'smooth'})};
 return <main className="appShell"><aside className="appSidebar"><div className="brandMark"><span>G</span><div><strong>GrowthOS</strong><small>Website growth control plane</small></div></div><nav aria-label="Primary navigation">{nav.map(([id,label,icon])=><button key={id} className={section===id?'sideNav active':'sideNav'} onClick={()=>go(id)}><span aria-hidden="true">{icon}</span>{label}</button>)}</nav><div className="sidebarFooter"><span className="statusDot"/>Control plane</div></aside><section className="appContent"><header className="appHeader"><div><p className="eyebrow">{section==='home'?'PORTFOLIO OVERVIEW':section.toUpperCase()}</p><h1>{section==='home'?'Good morning':section==='websites'?'Websites':section==='growth'?'Growth':section==='automation'?'Automation':'Settings'}</h1><p className="lede">{section==='home'?'See what matters, what needs attention and what GrowthOS recommends next.':section==='websites'?'Inspect each website without mixing portfolio and system controls.':section==='growth'?'Turn verified evidence into measurable growth actions.':section==='automation'?'Run and verify governed work without exposing internal complexity.':'Advanced governance lives here, away from daily growth work.'}</p></div><div className="headerTools"><label htmlFor="website-scope">Website</label><select id="website-scope" value={siteId} onChange={e=>setSiteId(e.target.value)}>{siteScopeOptions(sites).map(o=><option key={o.value||'all'} value={o.value}>{o.label}</option>)}</select></div></header>{error&&<div className="alert"><strong>Portfolio data unavailable</strong><span>{error}</span></div>}{loading&&<div className="loadingBar" aria-live="polite">Updating portfolio data…</div>}{section==='home'&&<Home snapshot={snapshot} counts={counts} approvals={approvals} go={go}/>} {section==='websites'&&<Websites snapshot={snapshot} siteId={siteId} selectedSite={selectedSite} setSiteId={setSiteId}/>} {section==='growth'&&<Growth snapshot={snapshot} counts={counts} approvals={approvals}/>} {section==='automation'&&<Automation snapshot={snapshot} counts={counts}/>} {section==='settings'&&<Settings snapshot={snapshot}/>}</section><nav className="mobileNav" aria-label="Mobile navigation">{nav.map(([id,label,icon])=><button key={id} className={section===id?'active':''} onClick={()=>go(id)}><span aria-hidden="true">{icon}</span><small>{label}</small></button>)}</nav></main>;
}
function Summary({title,value,detail,action,onClick}:{title:string;value:number|string;detail:string;action:string;onClick:()=>void}){return <article className="summaryCard"><span>{title}</span><strong>{value}</strong><small>{detail}</small><button type="button" onClick={onClick}>{action} →</button></article>}
function Home({snapshot,counts,approvals,go}:{snapshot:DashboardSnapshot|null;counts:DashboardSnapshot['counts']|undefined;approvals:ReturnType<typeof buildApprovalInboxViewModel>;go:(s:Section)=>void}){const websiteCount=snapshot?snapshot.sites.length:'—'; const liveSites=snapshot?snapshot.sites:[]; const rows=liveSites;const attention=(counts?.needsApproval??0)+(counts?.exceptions??0)+(counts?.qaFailed??0);return <div className="pageStack"><section className="heroSummary"><div><span className="kicker">Portfolio health</span><h2>{websiteCount} websites <span className="muted">·</span> {attention?attention+' need attention':'No urgent items'}</h2><p>Verified issues and governed actions are surfaced here first.</p></div><button type="button" onClick={()=>go('websites')}>View websites →</button></section><section><div className="sectionTitle"><div><h2>Needs your attention</h2><p>Only items that require a decision or follow-up.</p></div></div><div className="attentionGrid"><Summary title="Approvals" value={counts?.needsApproval??'—'} detail="Decisions waiting" action="Review" onClick={()=>go('growth')}/><Summary title="Website issues" value={(counts?.qaFailed??0)+(counts?.exceptions??0)||'—'} detail="QA or exceptions" action="Inspect" onClick={()=>go('websites')}/><Summary title="Active work" value={counts?.activeJobs??'—'} detail="Queued or running" action="View" onClick={()=>go('automation')}/></div></section><section><div className="sectionTitle"><div><h2>Websites</h2><p>Your portfolio at a glance.</p></div><button type="button" className="textButton" onClick={()=>go('websites')}>View all →</button></div><div className="siteRows">{rows.slice(0,6).map(site=><div className="siteRow" key={site.id}><div className="siteAvatar">{site.name.slice(0,1)}</div><div className="siteRowMain"><strong>{site.name}</strong><span>{site.domain}</span></div><span className="healthBadge">{site.status}</span></div>)}{!rows.length&&<div className="emptyState">No website data is available for this scope.</div>}</div></section><section><div className="sectionTitle"><div><h2>Next best actions</h2><p>Evidence-backed opportunities ready for review.</p></div><button type="button" className="textButton" onClick={()=>go('growth')}>Open Growth →</button></div><div className="actionList">{(snapshot?.nextBestActions??[]).slice(0,4).map((a,i)=><div className="actionRow" key={a.id}><span className="rank">{i+1}</span><div><strong>{a.title}</strong><span>{a.category} · score {a.score}</span></div><span className="actionArrow">→</span></div>)}{!(snapshot?.nextBestActions?.length)&&<div className="emptyState">No verified growth actions are available.</div>}</div></section><section className="activityStrip"><div><strong>Approvals</strong><span>{approvals.length} pending decisions</span></div><button type="button" onClick={()=>go('growth')}>Review inbox →</button></section></div>}
function Websites({snapshot,siteId,selectedSite,setSiteId}:{snapshot:DashboardSnapshot|null;siteId:string;selectedSite:any;setSiteId:(v:string)=>void}){const rows=snapshot?snapshot.sites:[];return <div className="pageStack"><div className="filterBar"><div><strong>{selectedSite?'Website overview':'All websites'}</strong><span>{selectedSite?selectedSite.name:'Select a website for focused detail.'}</span></div><button type="button" disabled aria-describedby="add-site-help" className="secondary">+ Add website</button><small id="add-site-help">Website onboarding is not available from this command center yet.</small><select value={siteId} onChange={e=>setSiteId(e.target.value)}>{siteScopeOptions(sites).map(o=><option key={o.value||'all'} value={o.value}>{o.label}</option>)}</select></div>{selectedSite?<WebsiteDetail site={selectedSite} snapshot={snapshot}/>:<div className="websiteGrid">{rows.map(site=><button type="button" className="websiteCard" key={site.id} onClick={()=>setSiteId(site.id)}><div className="siteAvatar large">{site.name.slice(0,1)}</div><div><h2>{site.name}</h2><p>{site.domain}</p></div><span className="healthBadge">{site.status}</span><span className="cardArrow">→</span></button>)}</div>}</div>}
function WebsiteDetail({site,snapshot}:{site:any;snapshot:DashboardSnapshot|null}){const next=(snapshot?.nextBestActions??[]).filter(a=>a.siteId===site.id).slice(0,4);return <div className="detailStack"><section className="detailHero"><div><span className="kicker">Website</span><h2>{site.name}</h2><p>{site.domain}</p></div><span className="healthBadge">{site.status}</span></section><div className="miniStats"><Summary title="Open opportunities" value={next.length} detail="Verified actions" action="Growth" onClick={()=>{}}/><Summary title="Active jobs" value={snapshot?.activeJobs??'—'} detail="Current workload" action="Activity" onClick={()=>{}}/></div><section className="simplePanel"><h3>Growth areas</h3><div className="topicGrid">{growthAreas.map(x=><div key={x}><strong>{x}</strong><span>Open detailed workspace →</span></div>)}</div></section><section className="simplePanel"><h3>Next best actions</h3>{next.length?next.map(a=><div className="actionRow" key={a.id}><div><strong>{a.title}</strong><span>{a.category} · score {a.score}</span></div><button type="button">Review</button></div>):<div className="emptyState">No verified actions for this website.</div>}</section></div>}
function Growth({snapshot,counts,approvals}:{snapshot:DashboardSnapshot|null;counts:DashboardSnapshot['counts']|undefined;approvals:ReturnType<typeof buildApprovalInboxViewModel>}){return <div className="pageStack"><section className="heroSummary compact"><div><span className="kicker">Growth intelligence</span><h2>{snapshot?.nextBestActions.length??'—'} verified opportunities</h2><p>SEO, CRO, competitors, content and revenue are grouped around decisions instead of separate dashboards.</p></div></section><div className="topicGrid five">{growthAreas.map((x,i)=><div key={x}><span className="topicIndex">0{i+1}</span><strong>{x}</strong><span>{i===0?'Technical issues and visibility':i===1?'Conversion opportunities':i===2?'Market and package gaps':i===3?'Content and lifecycle':'Attribution and impact'}</span><button type="button">Explore →</button></div>)}</div><section className="simplePanel"><div className="sectionTitle"><div><h2>Approval inbox</h2><p>{approvals.length} decisions need review.</p></div><span className="countPill">{counts?.needsApproval??'—'}</span></div><ApprovalInboxPanel items={approvals}/></section></div>}
function Automation({snapshot,counts}:{snapshot:DashboardSnapshot|null;counts:DashboardSnapshot['counts']|undefined}){return <div className="pageStack"><section className="heroSummary compact"><div><span className="kicker">Automation</span><h2>{counts?.activeJobs??'—'} active jobs</h2><p>Execution and verification stay together so operational state is easy to understand.</p></div></section><div className="attentionGrid"><Summary title="Queued & running" value={counts?.activeJobs??'—'} detail="Current workload" action="Inspect" onClick={()=>{}}/><Summary title="Approvals" value={counts?.needsApproval??'—'} detail="Before execution" action="Review" onClick={()=>{}}/><Summary title="Integrations" value={snapshot?.integrations.length??'—'} detail="Connector status" action="Check" onClick={()=>{}}/></div><section className="simplePanel"><h2>Execution model</h2><div className="flow">{['Discover','Verify','Recommend','Approve','Execute','Measure'].map((x,i)=><span key={x}><b>{x}</b>{i<5&&<i>→</i>}</span>)}</div></section></div>}
function Settings({snapshot}:{snapshot:DashboardSnapshot|null}){const items=settingsAreas;return <div className="pageStack"><section className="heroSummary compact"><div><span className="kicker">System</span><h2>Control how GrowthOS operates</h2><p>Advanced governance stays here instead of competing with daily growth work.</p></div></section><div className="settingsGrid">{items.map(x=><article key={x}><span className="settingsIcon">{x[0]}</span><h2>{x}</h2><p>{x==='Connections'?'Connector health and external prerequisites':x==='Features & plans'?'Free, Pro and Business capability controls':x==='Security & audit'?'RBAC, audit, recovery and access controls':'Deployment, readiness and system health'}</p><button type="button">Open →</button></article>)}</div><section className="simplePanel"><h3>Current connections</h3>{snapshot?.integrations?.length?snapshot.integrations.map(x=><div className="connectionRow" key={x.name}><span>{x.name}</span><strong className={x.status==='healthy'?'good':'warn'}>{x.status}</strong><small>{x.detail}</small></div>):<div className="emptyState">Connection status is not available yet.</div>}</section></div>}
